version: '3'
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    environment: ['CLI_JAVA_OPTS=-Xms2g -Xmx2g','bootstrap.memory_lock=true','discovery.type=single-node','xpack.security.enabled=false', 'xpack.security.enrollment.enabled=false']
    ports:
      - 9200:9200

#  kibana:
#    image: docker.elastic.co/kibana/kibana:8.7.1
#    container_name: kibana
#    environment:
#      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: d1a66dfd-c4d3-4a0a-8290-2abcb83ab3aa
#    ports:
#      - 5601:5601


  elastic:
    image: elastichq/elasticsearch-hq
    restart: unless-stopped
    container_name: elastichq
    environment:
      - HQ_DEFAULT_URL=http://host.docker.internal:9200
      - HQ_DEBUG=True
      - HQ_ENABLE_SSL=False
      - HQ_VERIFY_CERTS=False
    ports:
      - "5000:5000"

  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    ports:
      - "5111:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=search