"""empty message

Revision ID: 560bd2cb4298
Revises: 
Create Date: 2024-06-14 16:25:53.154064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560bd2cb4298'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_one',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('source_txt1', sa.String(), nullable=False),
    sa.Column('source_txt2', sa.String(), nullable=False),
    sa.Column('source_txt3', sa.String(), nullable=False),
    sa.Column('source_txt4', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('entity_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='source'
    )
    op.create_index(op.f('ix_source_text_one_id'), 'text_one', ['id'], unique=True, schema='source')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_text_one_id'), table_name='text_one', schema='source')
    op.drop_table('text_one', schema='source')
    # ### end Alembic commands ###
